services:
  - type: web
    name: sillage-perfum-ecommerce
    env: node
    plan: free
    buildCommand: bun install && bun run build
    startCommand: bun run preview --host 0.0.0.0 --port $PORT
    publishDir: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html