import { apiClient } from '@/lib/apiClient';

// Lista completa de productos Sillage Perfums
const zacharProducts = [
  {
    "name": "Inspirado en 212 MEN - 30ml",
    "description": "Fragancia sofisticada y moderna. Con un aroma fresco y especiado, este perfume captura la esencia de la elegancia contemporánea. Su intensidad moderada lo hace versátil para cualquier ocasión, mientras que su inspiración en 212 MEN le confiere una personalidad magnética y carismática.",
    "price": 9000,
    "sku": "ZP1H-30ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "30ml",
    "concentration": "Eau de Parfum",
    "notes": "Notas verdes, toronja, especias, bergamota, lavanda, petit grain, jengibre, violeta, gardenia, salvia, almizcle, sándalo, incienso, madera de gaiac, vetiver, ládano",
    "duration": "6-8 horas",
    "original_inspiration": "212 MEN",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en 212 MEN - 50ml",
    "description": "Fragancia sofisticada y moderna. Con un aroma fresco y especiado, este perfume captura la esencia de la elegancia contemporánea. Su intensidad moderada lo hace versátil para cualquier ocasión, mientras que su inspiración en 212 MEN le confiere una personalidad magnética y carismática.",
    "price": 14000,
    "sku": "ZP1H-50ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "50ml",
    "concentration": "Eau de Parfum",
    "notes": "Notas verdes, toronja, especias, bergamota, lavanda, petit grain, jengibre, violeta, gardenia, salvia, almizcle, sándalo, incienso, madera de gaiac, vetiver, ládano",
    "duration": "6-8 horas",
    "original_inspiration": "212 MEN",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en 212 MEN - 100ml",
    "description": "Fragancia sofisticada y moderna. Con un aroma fresco y especiado, este perfume captura la esencia de la elegancia contemporánea. Su intensidad moderada lo hace versátil para cualquier ocasión, mientras que su inspiración en 212 MEN le confiere una personalidad magnética y carismática.",
    "price": 18000,
    "sku": "ZP1H-100ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "100ml",
    "concentration": "Eau de Parfum",
    "notes": "Notas verdes, toronja, especias, bergamota, lavanda, petit grain, jengibre, violeta, gardenia, salvia, almizcle, sándalo, incienso, madera de gaiac, vetiver, ládano",
    "duration": "6-8 horas",
    "original_inspiration": "212 MEN",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en 212 SEXY MEN - 30ml",
    "description": "Fragancia seductora y sofisticada. Con un aroma envolvente y una intensidad equilibrada, este perfume captura la esencia de la elegancia urbana. Inspirado en la sensualidad de 212 SEXY MEN, es versátil y se adapta a cualquier ocasión, reflejando una personalidad magnética y segura.",
    "price": 9000,
    "sku": "ZP2H-30ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "30ml",
    "concentration": "Eau de Parfum",
    "notes": "Mandarina, bergamota, notas verdes, pimienta, flores, cardamomo, vainilla, madera de gaiac, sándalo, almizcle, ámbar",
    "duration": "6-8 horas",
    "original_inspiration": "212 SEXY MEN",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en 212 SEXY MEN - 50ml",
    "description": "Fragancia seductora y sofisticada. Con un aroma envolvente y una intensidad equilibrada, este perfume captura la esencia de la elegancia urbana. Inspirado en la sensualidad de 212 SEXY MEN, es versátil y se adapta a cualquier ocasión, reflejando una personalidad magnética y segura.",
    "price": 14000,
    "sku": "ZP2H-50ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "50ml",
    "concentration": "Eau de Parfum",
    "notes": "Mandarina, bergamota, notas verdes, pimienta, flores, cardamomo, vainilla, madera de gaiac, sándalo, almizcle, ámbar",
    "duration": "6-8 horas",
    "original_inspiration": "212 SEXY MEN",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en 212 SEXY MEN - 100ml",
    "description": "Fragancia seductora y sofisticada. Con un aroma envolvente y una intensidad equilibrada, este perfume captura la esencia de la elegancia urbana. Inspirado en la sensualidad de 212 SEXY MEN, es versátil y se adapta a cualquier ocasión, reflejando una personalidad magnética y segura.",
    "price": 18000,
    "sku": "ZP2H-100ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "100ml",
    "concentration": "Eau de Parfum",
    "notes": "Mandarina, bergamota, notas verdes, pimienta, flores, cardamomo, vainilla, madera de gaiac, sándalo, almizcle, ámbar",
    "duration": "6-8 horas",
    "original_inspiration": "212 SEXY MEN",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en 212 VIP MEN - 30ml",
    "description": "Una fragancia sofisticada y audaz. Este aroma Aromático Amaderado fusiona la frescura vibrante de la lima y el jengibre con la calidez envolvente del ámbar y el cuero, creando un contraste irresistible. Ideal para hombres que buscan un aroma distintivo y duradero que refleje su personalidad única y sofisticada.",
    "price": 9000,
    "sku": "ZP4H-30ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "30ml",
    "concentration": "Eau de Parfum",
    "notes": "Lima, limón, bergamota, jazmín, naranja, mandarina, nerolí, notas marinas, jazmín, calone, durazno, fresia, jacinto, romero, ciclamen, violeta, cilantro, nuez moscada, rosa, reseda, almizcle blanco, cedro, musgo de roble, pachulí, ámbar",
    "duration": "6-8 horas",
    "original_inspiration": "212 VIP MEN",
    "in_stock": true,
    "is_active": true
  },


  {
    "name": "Inspirado en 212 VIP MEN - 50ml",
    "description": "Una fragancia sofisticada y audaz. Este aroma Aromático Amaderado fusiona la frescura vibrante de la lima y el jengibre con la calidez envolvente del ámbar y el cuero, creando un contraste irresistible. Ideal para hombres que buscan un aroma distintivo y duradero que refleje su personalidad única y sofisticada.",
    "price": 14000,
    "sku": "ZP4H-50ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "50ml",
    "concentration": "Eau de Parfum",
    "notes": "Lima, limón, bergamota, jazmín, naranja, mandarina, nerolí, notas marinas, jazmín, calone, durazno, fresia, jacinto, romero, ciclamen, violeta, cilantro, nuez moscada, rosa, reseda, almizcle blanco, cedro, musgo de roble, pachulí, ámbar",
    "duration": "6-8 horas",
    "original_inspiration": "212 VIP MEN",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en 212 VIP MEN - 100ml",
    "description": "Una fragancia sofisticada y audaz. Este aroma Aromático Amaderado fusiona la frescura vibrante de la lima y el jengibre con la calidez envolvente del ámbar y el cuero, creando un contraste irresistible. Ideal para hombres que buscan un aroma distintivo y duradero que refleje su personalidad única y sofisticada.",
    "price": 18000,
    "sku": "ZP4H-100ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "100ml",
    "concentration": "Eau de Parfum",
    "notes": "Lima, limón, bergamota, jazmín, naranja, mandarina, nerolí, notas marinas, jazmín, calone, durazno, fresia, jacinto, romero, ciclamen, violeta, cilantro, nuez moscada, rosa, reseda, almizcle blanco, cedro, musgo de roble, pachulí, ámbar",
    "duration": "6-8 horas",
    "original_inspiration": "212 VIP MEN",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en ACQUA DI GIO - 30ml",
    "description": "Fragancia fresca y sofisticada que captura la esencia del hombre moderno. Con un aroma acuático y cítrico, este perfume ofrece una intensidad equilibrada que evoca libertad y elegancia. Inspirado en la brisa marina y la frescura de los cítricos, ideal para el hombre seguro de sí mismo que busca un toque de distinción en su día a día.",
    "price": 9000,
    "sku": "ZP5H-30ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "30ml",
    "concentration": "Eau de Parfum",
    "notes": "Lima, limón, bergamota, jazmín, naranja, mandarina, nerolí, notas marinas, jazmín, calone, durazno, fresia, jacinto, romero, ciclamen, violeta, cilantro, nuez moscada, rosa, reseda, almizcle blanco, cedro, musgo de roble, pachulí, ámbar",
    "duration": "6-8 horas",
    "original_inspiration": "ACQUA DI GIO",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en ACQUA DI GIO - 50ml",
    "description": "Fragancia fresca y sofisticada que captura la esencia del hombre moderno. Con un aroma acuático y cítrico, este perfume ofrece una intensidad equilibrada que evoca libertad y elegancia. Inspirado en la brisa marina y la frescura de los cítricos, ideal para el hombre seguro de sí mismo que busca un toque de distinción en su día a día.",
    "price": 14000,
    "sku": "ZP5H-50ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "50ml",
    "concentration": "Eau de Parfum",
    "notes": "Lima, limón, bergamota, jazmín, naranja, mandarina, nerolí, notas marinas, jazmín, calone, durazno, fresia, jacinto, romero, ciclamen, violeta, cilantro, nuez moscada, rosa, reseda, almizcle blanco, cedro, musgo de roble, pachulí, ámbar",
    "duration": "6-8 horas",
    "original_inspiration": "ACQUA DI GIO",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en ACQUA DI GIO - 100ml",
    "description": "Fragancia fresca y sofisticada que captura la esencia del hombre moderno. Con un aroma acuático y cítrico, este perfume ofrece una intensidad equilibrada que evoca libertad y elegancia. Inspirado en la brisa marina y la frescura de los cítricos, ideal para el hombre seguro de sí mismo que busca un toque de distinción en su día a día.",
    "price": 18000,
    "sku": "ZP5H-100ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "100ml",
    "concentration": "Eau de Parfum",
    "notes": "Lima, limón, bergamota, jazmín, naranja, mandarina, nerolí, notas marinas, jazmín, calone, durazno, fresia, jacinto, romero, ciclamen, violeta, cilantro, nuez moscada, rosa, reseda, almizcle blanco, cedro, musgo de roble, pachulí, ámbar",
    "duration": "6-8 horas",
    "original_inspiration": "ACQUA DI GIO",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en ANGEL - 30ml",
    "description": "Fragancia audaz y sofisticada. Con un aroma que combina la frescura de las notas verdes y afrutadas con la calidez de las especias, este perfume ofrece una intensidad envolvente y una versatilidad que lo hace perfecto para cualquier ocasión. Inspirado en la esencia de ANGEL MEN, es ideal para aquellos que desean expresar su personalidad única y carismática.",
    "price": 9000,
    "sku": "ZP7H-30ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "30ml",
    "concentration": "Eau de Parfum",
    "notes": "Lavanda, menta, notas afrutadas y especias, cilantro, notas verdes, bergamota, caramelo, pachulí, miel, leche, cedro, jazmín, lirio de los valles, café, pachulí, vainilla, haba tonka, benjuí, ámbar, sándalo, almizcle",
    "duration": "6-8 horas",
    "original_inspiration": "ANGEL",
    "in_stock": true,
    "is_active": true
  },

  {
    "name": "Inspirado en ANGEL - 50ml",
    "description": "Fragancia audaz y sofisticada. Con un aroma que combina la frescura de las notas verdes y afrutadas con la calidez de las especias, este perfume ofrece una intensidad envolvente y una versatilidad que lo hace perfecto para cualquier ocasión. Inspirado en la esencia de ANGEL MEN, es ideal para aquellos que desean expresar su personalidad única y carismática.",
    "price": 14000,
    "sku": "ZP7H-50ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "50ml",
    "concentration": "Eau de Parfum",
    "notes": "Lavanda, menta, notas afrutadas y especias, cilantro, notas verdes, bergamota, caramelo, pachulí, miel, leche, cedro, jazmín, lirio de los valles, café, pachulí, vainilla, haba tonka, benjuí, ámbar, sándalo, almizcle",
    "duration": "6-8 horas",
    "original_inspiration": "ANGEL",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en ANGEL - 100ml",
    "description": "Fragancia audaz y sofisticada. Con un aroma que combina la frescura de las notas verdes y afrutadas con la calidez de las especias, este perfume ofrece una intensidad envolvente y una versatilidad que lo hace perfecto para cualquier ocasión. Inspirado en la esencia de ANGEL MEN, es ideal para aquellos que desean expresar su personalidad única y carismática.",
    "price": 18000,
    "sku": "ZP7H-100ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "100ml",
    "concentration": "Eau de Parfum",
    "notes": "Lavanda, menta, notas afrutadas y especias, cilantro, notas verdes, bergamota, caramelo, pachulí, miel, leche, cedro, jazmín, lirio de los valles, café, pachulí, vainilla, haba tonka, benjuí, ámbar, sándalo, almizcle",
    "duration": "6-8 horas",
    "original_inspiration": "ANGEL",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en ARMANI CODE SPORT - 30ml",
    "description": "Fragancia vibrante y enérgica. Con un aroma que evoca la libertad y la aventura, este perfume ofrece una intensidad moderada. Inspirado en la esencia deportiva de Armani Code Sport, es versátil y refleja una personalidad dinámica y segura.",
    "price": 9000,
    "sku": "ZP9H-30ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "30ml",
    "concentration": "Eau de Parfum",
    "notes": "Menta, mandarina, limón, flor de jengibre, vetiver, notas acuáticas, ámbar",
    "duration": "6-8 horas",
    "original_inspiration": "ARMANI CODE SPORT",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en ARMANI CODE SPORT - 50ml",
    "description": "Fragancia vibrante y enérgica. Con un aroma que evoca la libertad y la aventura, este perfume ofrece una intensidad moderada. Inspirado en la esencia deportiva de Armani Code Sport, es versátil y refleja una personalidad dinámica y segura.",
    "price": 14000,
    "sku": "ZP9H-50ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "50ml",
    "concentration": "Eau de Parfum",
    "notes": "Menta, mandarina, limón, flor de jengibre, vetiver, notas acuáticas, ámbar",
    "duration": "6-8 horas",
    "original_inspiration": "ARMANI CODE SPORT",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en ARMANI CODE SPORT - 100ml",
    "description": "Fragancia vibrante y enérgica. Con un aroma que evoca la libertad y la aventura, este perfume ofrece una intensidad moderada. Inspirado en la esencia deportiva de Armani Code Sport, es versátil y refleja una personalidad dinámica y segura.",
    "price": 18000,
    "sku": "ZP9H-100ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "100ml",
    "concentration": "Eau de Parfum",
    "notes": "Menta, mandarina, limón, flor de jengibre, vetiver, notas acuáticas, ámbar",
    "duration": "6-8 horas",
    "original_inspiration": "ARMANI CODE SPORT",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en BOSS 6 - 30ml",
    "description": "Fragancia sofisticada y versátil, ideal para el hombre moderno que busca un equilibrio entre elegancia y frescura. Con una intensidad moderada, este perfume se inspira en la esencia clásica de BOSS 6, ofreciendo un aroma que combina notas frutales y amaderadas, perfecto para cualquier ocasión. Su personalidad es decidida y carismática.",
    "price": 9000,
    "sku": "ZP13H-30ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "30ml",
    "concentration": "Eau de Parfum",
    "notes": "Manzana, ciruela, bergamota, limón, musgo de roble, geranio, canela, caoba, clavel, vainilla, sándalo, cedro, vetiver, olivo",
    "duration": "6-8 horas",
    "original_inspiration": "BOSS 6",
    "in_stock": true,
    "is_active": true
  },

  {
    "name": "Inspirado en BOSS 6 - 50ml",
    "description": "Fragancia sofisticada y versátil, ideal para el hombre moderno que busca un equilibrio entre elegancia y frescura. Con una intensidad moderada, este perfume se inspira en la esencia clásica de BOSS 6, ofreciendo un aroma que combina notas frutales y amaderadas, perfecto para cualquier ocasión. Su personalidad es decidida y carismática.",
    "price": 14000,
    "sku": "ZP13H-50ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "50ml",
    "concentration": "Eau de Parfum",
    "notes": "Manzana, ciruela, bergamota, limón, musgo de roble, geranio, canela, caoba, clavel, vainilla, sándalo, cedro, vetiver, olivo",
    "duration": "6-8 horas",
    "original_inspiration": "BOSS 6",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en BOSS 6 - 100ml",
    "description": "Fragancia sofisticada y versátil, ideal para el hombre moderno que busca un equilibrio entre elegancia y frescura. Con una intensidad moderada, este perfume se inspira en la esencia clásica de BOSS 6, ofreciendo un aroma que combina notas frutales y amaderadas, perfecto para cualquier ocasión. Su personalidad es decidida y carismática.",
    "price": 18000,
    "sku": "ZP13H-100ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "100ml",
    "concentration": "Eau de Parfum",
    "notes": "Manzana, ciruela, bergamota, limón, musgo de roble, geranio, canela, caoba, clavel, vainilla, sándalo, cedro, vetiver, olivo",
    "duration": "6-8 horas",
    "original_inspiration": "BOSS 6",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en BLEU CHANEL - 30ml",
    "description": "Fragancia sofisticada y moderna, con un aroma distintivo y versátil. Con una intensidad equilibrada, este perfume captura la esencia de la elegancia contemporánea. Inspirado en la icónica BLEU CHANEL, adaptándose a la perfección a la personalidad de un hombre dinámico y refinado.",
    "price": 9000,
    "sku": "ZP17H-30ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "30ml",
    "concentration": "Eau de Parfum",
    "notes": "Pomelo, limón, menta, pimienta rosa, jengibre, nuez moscada, jazmín, Iso E Super, incienso, vetiver, cedro, sándalo, pachulí, ládano, almizcle blanco",
    "duration": "6-8 horas",
    "original_inspiration": "BLEU CHANEL",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en BLEU CHANEL - 50ml",
    "description": "Fragancia sofisticada y moderna, con un aroma distintivo y versátil. Con una intensidad equilibrada, este perfume captura la esencia de la elegancia contemporánea. Inspirado en la icónica BLEU CHANEL, adaptándose a la perfección a la personalidad de un hombre dinámico y refinado.",
    "price": 14000,
    "sku": "ZP17H-50ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "50ml",
    "concentration": "Eau de Parfum",
    "notes": "Pomelo, limón, menta, pimienta rosa, jengibre, nuez moscada, jazmín, Iso E Super, incienso, vetiver, cedro, sándalo, pachulí, ládano, almizcle blanco",
    "duration": "6-8 horas",
    "original_inspiration": "BLEU CHANEL",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en BLEU CHANEL - 100ml",
    "description": "Fragancia sofisticada y moderna, con un aroma distintivo y versátil. Con una intensidad equilibrada, este perfume captura la esencia de la elegancia contemporánea. Inspirado en la icónica BLEU CHANEL, adaptándose a la perfección a la personalidad de un hombre dinámico y refinado.",
    "price": 18000,
    "sku": "ZP17H-100ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "100ml",
    "concentration": "Eau de Parfum",
    "notes": "Pomelo, limón, menta, pimienta rosa, jengibre, nuez moscada, jazmín, Iso E Super, incienso, vetiver, cedro, sándalo, pachulí, ládano, almizcle blanco",
    "duration": "6-8 horas",
    "original_inspiration": "BLEU CHANEL",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en ETERNITY - 30ml",
    "description": "Fragancia sofisticada y atemporal. Con un aroma fresco y envolvente, este perfume ofrece una intensidad equilibrada que lo hace perfecto para cualquier ocasión. Inspirado en la eternidad de los momentos inolvidables, es versátil y refleja una personalidad segura y carismática.",
    "price": 9000,
    "sku": "ZP32H-30ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "30ml",
    "concentration": "Eau de Parfum",
    "notes": "Lavanda, limón, bergamota, mandarina, salvia, bayas de enebro, albahaca, geranio, cilantro, jazmín, flor de azahar, azucena, lirio de los valles, sándalo, vetiver, almizcle, palo de rosa de Brasil, ámbar",
    "duration": "6-8 horas",
    "original_inspiration": "ETERNITY",
    "in_stock": true,
    "is_active": true
  },

  {
    "name": "Inspirado en ETERNITY - 50ml",
    "description": "Fragancia sofisticada y atemporal. Con un aroma fresco y envolvente, este perfume ofrece una intensidad equilibrada que lo hace perfecto para cualquier ocasión. Inspirado en la eternidad de los momentos inolvidables, es versátil y refleja una personalidad segura y carismática.",
    "price": 14000,
    "sku": "ZP32H-50ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "50ml",
    "concentration": "Eau de Parfum",
    "notes": "Lavanda, limón, bergamota, mandarina, salvia, bayas de enebro, albahaca, geranio, cilantro, jazmín, flor de azahar, azucena, lirio de los valles, sándalo, vetiver, almizcle, palo de rosa de Brasil, ámbar",
    "duration": "6-8 horas",
    "original_inspiration": "ETERNITY",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en ETERNITY - 100ml",
    "description": "Fragancia sofisticada y atemporal. Con un aroma fresco y envolvente, este perfume ofrece una intensidad equilibrada que lo hace perfecto para cualquier ocasión. Inspirado en la eternidad de los momentos inolvidables, es versátil y refleja una personalidad segura y carismática.",
    "price": 18000,
    "sku": "ZP32H-100ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "100ml",
    "concentration": "Eau de Parfum",
    "notes": "Lavanda, limón, bergamota, mandarina, salvia, bayas de enebro, albahaca, geranio, cilantro, jazmín, flor de azahar, azucena, lirio de los valles, sándalo, vetiver, almizcle, palo de rosa de Brasil, ámbar",
    "duration": "6-8 horas",
    "original_inspiration": "ETERNITY",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en HUGO BOSS - 30ml",
    "description": "Fragancia sofisticada y moderna, que busca un aroma distintivo y versátil. Con una intensidad equilibrada, este perfume se inspira en la elegancia atemporal de HUGO BOSS, ofreciendo una experiencia olfativa que combina frescura y calidez.",
    "price": 9000,
    "sku": "ZP38H-30ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "30ml",
    "concentration": "Eau de Parfum",
    "notes": "Manzana verde, menta, lavanda, pomelo, albahaca, salvia, geranio, clavel, jazmín, abeto, cedro, pachulí",
    "duration": "6-8 horas",
    "original_inspiration": "HUGO BOSS",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en HUGO BOSS - 50ml",
    "description": "Fragancia sofisticada y moderna, que busca un aroma distintivo y versátil. Con una intensidad equilibrada, este perfume se inspira en la elegancia atemporal de HUGO BOSS, ofreciendo una experiencia olfativa que combina frescura y calidez.",
    "price": 14000,
    "sku": "ZP38H-50ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "50ml",
    "concentration": "Eau de Parfum",
    "notes": "Manzana verde, menta, lavanda, pomelo, albahaca, salvia, geranio, clavel, jazmín, abeto, cedro, pachulí",
    "duration": "6-8 horas",
    "original_inspiration": "HUGO BOSS",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en HUGO BOSS - 100ml",
    "description": "Fragancia sofisticada y moderna, que busca un aroma distintivo y versátil. Con una intensidad equilibrada, este perfume se inspira en la elegancia atemporal de HUGO BOSS, ofreciendo una experiencia olfativa que combina frescura y calidez.",
    "price": 18000,
    "sku": "ZP38H-100ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "100ml",
    "concentration": "Eau de Parfum",
    "notes": "Manzana verde, menta, lavanda, pomelo, albahaca, salvia, geranio, clavel, jazmín, abeto, cedro, pachulí",
    "duration": "6-8 horas",
    "original_inspiration": "HUGO BOSS",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en INVICTUS - 30ml",
    "description": "Fragancia audaz y dinámica. Con una intensidad que deja huella, este perfume se inspira en la victoria y la fuerza. Su aroma es una declaración de confianza y energía, ideal para quienes desean destacar con una personalidad vibrante y segura.",
    "price": 9000,
    "sku": "ZP42H-30ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "30ml",
    "concentration": "Eau de Parfum",
    "notes": "Notas marinas, pomelo, mandarina, hoja de laurel, jazmín, ámbar gris, madera de gaiac, musgo de roble, pachulí",
    "duration": "6-8 horas",
    "original_inspiration": "INVICTUS",
    "in_stock": true,
    "is_active": true
  },

  {
    "name": "Inspirado en INVICTUS - 50ml",
    "description": "Fragancia audaz y dinámica. Con una intensidad que deja huella, este perfume se inspira en la victoria y la fuerza. Su aroma es una declaración de confianza y energía, ideal para quienes desean destacar con una personalidad vibrante y segura.",
    "price": 14000,
    "sku": "ZP42H-50ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "50ml",
    "concentration": "Eau de Parfum",
    "notes": "Notas marinas, pomelo, mandarina, hoja de laurel, jazmín, ámbar gris, madera de gaiac, musgo de roble, pachulí",
    "duration": "6-8 horas",
    "original_inspiration": "INVICTUS",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en INVICTUS - 100ml",
    "description": "Fragancia audaz y dinámica. Con una intensidad que deja huella, este perfume se inspira en la victoria y la fuerza. Su aroma es una declaración de confianza y energía, ideal para quienes desean destacar con una personalidad vibrante y segura.",
    "price": 18000,
    "sku": "ZP42H-100ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "100ml",
    "concentration": "Eau de Parfum",
    "notes": "Notas marinas, pomelo, mandarina, hoja de laurel, jazmín, ámbar gris, madera de gaiac, musgo de roble, pachulí",
    "duration": "6-8 horas",
    "original_inspiration": "INVICTUS",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en J.P.G Le Male - 30ml",
    "description": "Una fragancia exquisita y sofisticada que combina a la perfección aromas aromáticos, frescos y especiados. Las notas de salida de abrótano, lavanda y menta aportan una frescura inigualable, mientras que el corazón de alcaravea y flor de azahar añade una calidez envolvente que realza su carácter.",
    "price": 9000,
    "sku": "ZP45H-30ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "30ml",
    "concentration": "Eau de Parfum",
    "notes": "Lavanda, menta, bergamota, abrótano, cardamomo, canela, flor de azahar de naranjo, alcaravea, vainilla, haba tonka, ámbar, sándalo, cedro",
    "duration": "6-8 horas",
    "original_inspiration": "J.P.G Le Male",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en J.P.G Le Male - 50ml",
    "description": "Una fragancia exquisita y sofisticada que combina a la perfección aromas aromáticos, frescos y especiados. Las notas de salida de abrótano, lavanda y menta aportan una frescura inigualable, mientras que el corazón de alcaravea y flor de azahar añade una calidez envolvente que realza su carácter.",
    "price": 14000,
    "sku": "ZP45H-50ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "50ml",
    "concentration": "Eau de Parfum",
    "notes": "Lavanda, menta, bergamota, abrótano, cardamomo, canela, flor de azahar de naranjo, alcaravea, vainilla, haba tonka, ámbar, sándalo, cedro",
    "duration": "6-8 horas",
    "original_inspiration": "J.P.G Le Male",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en J.P.G Le Male - 100ml",
    "description": "Una fragancia exquisita y sofisticada que combina a la perfección aromas aromáticos, frescos y especiados. Las notas de salida de abrótano, lavanda y menta aportan una frescura inigualable, mientras que el corazón de alcaravea y flor de azahar añade una calidez envolvente que realza su carácter.",
    "price": 18000,
    "sku": "ZP45H-100ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "100ml",
    "concentration": "Eau de Parfum",
    "notes": "Lavanda, menta, bergamota, abrótano, cardamomo, canela, flor de azahar de naranjo, alcaravea, vainilla, haba tonka, ámbar, sándalo, cedro",
    "duration": "6-8 horas",
    "original_inspiration": "J.P.G Le Male",
    "in_stock": true,
    "is_active": true
  },
  {
    "name": "Inspirado en LIGHT BLUE - 30ml",
    "description": "Fragancia vibrante y refrescante que captura la esencia del verano mediterráneo. Este perfume ofrece un aroma cítrico y amaderado que combina intensidad y frescura. Inspirado en la libertad y la aventura, reflejando una personalidad dinámica y enérgica.",
    "price": 9000,
    "sku": "ZP50H-30ML",
    "brand": "Sillage Perfums",
    "category": "Hombre",
    "image_url": "/images/sillapH.jpg",
    "stock_quantity": 50,
    "is_featured": false,
    "rating": 4.5,
    "size": "30ml",
    "concentration": "Eau de Parfum",
    "notes": "Pomelo, bergamota, mandarina siciliana, enebro de Virginia, pimienta, romero, palo de rosa de Brasil, almizcle, incienso, musgo de roble",
    "duration": "6-8 horas",
    "original_inspiration": "LIGHT BLUE",
    "in_stock": true,
    "is_active": true
  }
];

// Función para cargar productos nuevos de Sillage Perfums
export const loadNewZacharProducts = async () => {
  try {
    console.log('🔄 Cargando productos completos de Zachary...');

    // Llamar al endpoint del backend que maneja la carga de productos
    const response = await apiClient.post('/products/load-zachary');

    if (response.success) {
      console.log('✅ Productos de Zachary cargados exitosamente');
      return response.data || [];
    } else {
      throw new Error(response.error || 'Error cargando productos de Zachary');
    }
  } catch (error) {
    console.error('❌ Error cargando productos de Zachary:', error);
    throw error;
  }
};

// Función para obtener la lista completa de productos disponibles de Zachary
export const getZacharProductsList = () => {
  return zacharProducts;
};

// Función para cargar productos directamente (sin usar el backend)
export const loadZacharProductsDirectly = async () => {
  try {
    console.log('🔄 Cargando productos directamente...');

    let addedCount = 0;
    let errorCount = 0;

    for (const product of zacharProducts) {
      try {
        await apiClient.post('/products', product);
        addedCount++;
        console.log(`✅ Agregado: ${product.name}`);
      } catch (error) {
        errorCount++;
        console.error(`❌ Error con ${product.name}:`, error.message);
      }
    }

    console.log(`🎉 Proceso completado: ${addedCount} agregados, ${errorCount} errores`);

    return {
      success: true,
      addedCount,
      errorCount,
      total: zacharProducts.length
    };

  } catch (error) {
    console.error('❌ Error en carga directa:', error);
    throw error;
  }
};