[
    {
        "name": "Loción",
        "description": "Loción refrescante aguas de colonia, ideal para completar con tu Eau de Parfum.",
        "price": 6000,
        "sku": "SP52",
        "brand": "Sillage Perfum",
        "category": "Lociones",
        "image_url": "/images/locionM.jpg",
        "stock_quantity": 50,
        "is_featured": false,
        "rating": 4.5,
        "size": "120ml",
        "concentration": "Loción",
        "notes": "",
        "duration": "6-8 horas",
        "original_inspiration": "",
        "in_stock": true,
        "is_active": true
    },
    {
        "name": "Loción",
        "description": "Loción refrescante aguas de colonia, ideal para completar con tu Eau de Parfum.",
        "price": 6000,
        "sku": "SP55",
        "brand": "Sillage Perfum",
        "category": "Lociones",
        "image_url": "/images/locionM.jpg",
        "stock_quantity": 50,
        "is_featured": false,
        "rating": 4.5,
        "size": "120ml",
        "concentration": "Loción",
        "notes": "",
        "duration": "6-8 horas",
        "original_inspiration": "",
        "in_stock": true,
        "is_active": true
    },
    {
        "name": "Loción",
        "description": "Loción refrescante aguas de colonia, ideal para completar con tu Eau de Parfum.",
        "price": 6000,
        "sku": "SP89",
        "brand": "Sillage Perfum",
        "category": "Lociones",
        "image_url": "/images/locionM.jpg",
        "stock_quantity": 50,
        "is_featured": false,
        "rating": 4.5,
        "size": "120ml",
        "concentration": "Loción",
        "notes": "",
        "duration": "6-8 horas",
        "original_inspiration": "",
        "in_stock": true,
        "is_active": true
    },
    {
        "name": "Loción",
        "description": "Loción refrescante aguas de colonia, ideal para completar con tu Eau de Parfum.",
        "price": 6000,
        "sku": "SP90",
        "brand": "Sillage Perfum",
        "category": "Lociones",
        "image_url": "/images/locionM.jpg",
        "stock_quantity": 50,
        "is_featured": false,
        "rating": 4.5,
        "size": "120ml",
        "concentration": "Loción",
        "notes": "",
        "duration": "6-8 horas",
        "original_inspiration": "",
        "in_stock": true,
        "is_active": true
    },
    {
        "name": "Loción",
        "description": "Loción refrescante aguas de colonia, ideal para completar con tu Eau de Parfum.",
        "price": 6000,
        "sku": "SP4",
        "brand": "Sillage Perfum",
        "category": "Lociones",
        "image_url": "/images/locionH.jpg",
        "stock_quantity": 50,
        "is_featured": false,
        "rating": 4.5,
        "size": "120ml",
        "concentration": "Loción",
        "notes": "",
        "duration": "6-8 horas",
        "original_inspiration": "",
        "in_stock": true,
        "is_active": true
    },
    {
        "name": "Loción",
        "description": "Loción refrescante aguas de colonia, ideal para completar con tu Eau de Parfum.",
        "price": 6000,
        "sku": "SP5",
        "brand": "Sillage Perfum",
        "category": "Lociones",
        "image_url": "/images/locionH.jpg",
        "stock_quantity": 50,
        "is_featured": false,
        "rating": 4.5,
        "size": "120ml",
        "concentration": "Loción",
        "notes": "",
        "duration": "6-8 horas",
        "original_inspiration": "",
        "in_stock": true,
        "is_active": true
    },
    {
        "name": "Loción",
        "description": "Loción refrescante aguas de colonia, ideal para completar con tu Eau de Parfum.",
        "price": 6000,
        "sku": "SP42",
        "brand": "Sillage Perfum",
        "category": "Lociones",
        "image_url": "/images/locionH.jpg",
        "stock_quantity": 50,
        "is_featured": false,
        "rating": 4.5,
        "size": "120ml",
        "concentration": "Loción",
        "notes": "",
        "duration": "6-8 horas",
        "original_inspiration": "",
        "in_stock": true,
        "is_active": true
    },
    {
        "name": "Loción",
        "description": "Loción refrescante aguas de colonia, ideal para completar con tu Eau de Parfum.",
        "price": 6000,
        "sku": "SP53",
        "brand": "Sillage Perfum",
        "category": "Lociones",
        "image_url": "/images/locionH.jpg",
        "stock_quantity": 50,
        "is_featured": false,
        "rating": 4.5,
        "size": "120ml",
        "concentration": "Loción",
        "notes": "",
        "duration": "6-8 horas",
        "original_inspiration": "",
        "in_stock": true,
        "is_active": true
    }
]